name: CI/CD

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  empaquetado:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Script para empaquetar
        run: |
          conda activate splunk-app-packager
          py C:\Users\lpuentes\Documents\actions-runner\_work\packager_script\splunk_app_packager.py demo-app
          conda deactivate
        
#  ${{ github.repository }}
  instalacion:
    needs: empaquetado
    runs-on: self-hosted
#     environment: produccion
    steps:
      - name: Copiar paquete a destino
        run: |
          scp -i C:\Users\lpuentes\Downloads\llave.pem demo-app.tar.gz ${{secrets.USERNAME}}@${{secrets.HOST}}:Paquetes_Splunk
          curl -k https://${{ secrets.HOST }}:8089/services/apps/local -h "Authorization: Bearer ${{ secrets.TOKEN_AUTH }}" -d "filename=true" -d "name=/home/ec2-user/Paquetes_Splunk/demo-app.tar.gz" -d "update=false"
          
        
